### ISSUE TITLE
Start game button UI needs pre-click confirmation state

### ISSUE THREAD

**Issue by luluwelborn** [Astroknut/project1#2]
When a user mouses over the 'start game' button, a mouse hover or button hover state should appear to let the user know something will happen when they click.

**Comment by Astroknut** [comment]
With the Mission Updates text being hard to read, more than one person told me they didn't know how to start the game. But i've added text to the beginning of each round on the canvas asking the player to 'Click to start round', as well as removing the background image on the Mission Updates so its easier to read!
