### ISSUE TITLE
Development Issue

### ISSUE THREAD

**Issue by jayverts** [Astroknut/project1#3]
Can you indent your code a little better? I think it is only supposed to be 2 spaces. But I could be totally wrong. Everything just looks great it's hard to find issues!

**Comment by Astroknut** [comment]
Yeah for spaces its 2 spaces. But i'm sticking with tabs! :)
I appreciate all the feedback from you and Lauren! Hopefully by the time we start class tomorrow morning, I will have some style updates in place so it is a little more presentable!
